""" Constants and initialization maps """
import os
# Error messages


TRANSACTION_COST = 0.0075
ENVIRONMENT = os.getenv("ENVIRONMENT", "dry")

NO_MARKET_ERROR = "We couldn't find a market for the {}/{} pair. Try again?"

BUY_ORDER_DIRECTION = "BUY"
SELL_ORDER_DIRECTION = "SELL"

# EXECUTE MESSAGE TYPES
EXECUTE_PATH_TYPE = "PATH"
EXECUTE_RESULT_TYPE = "EXECRESULT"
EXECUTE_TOO_SOON_TYPE = "REPEATEDTOOSOON"
EXECUTE_API_TOO_MANY_ORDERS = "EXECUTE_SLOW_DOWN"
EXECUTE_UPDATE_OB = "UPDATE_OB"


# EVENTS
EVENT_OPPORTUNITY_FOUND = "EVENT_OPPORTUNITY_FOUND"
EVENT_EXECUTE_LOCK_SET = "EVENT_EXECUTE_LOCK_SET"
EVENT_OPPORTUNITY_SENT_TO_EXECUTOR = "EVENT_OPPORTUNITY_SENT_TO_EXECUTOR"
EVENT_EXECUTOR_RECEIVED_OPPORTUNITY = "EVENT_EXECUTOR_RECEIVED_OPPORTUNITY"
EVENT_ORDER_PLACED = "EVENT_ORDER_PLACED"
EVENT_ORDER_RESPONSE = "EVENT_ORDER_PLACED"
EVENT_TRADE = "EVENT_TRADE"
EVENT_MISSED_PATH = "EVENT_MISSED_PATH"
EVENT_COMPLETED_PATH = "EVENT_COMPLETED_PATH"
EVENT_EXECUTER_RESULT_TO_MAIN = "EVENT_EXECUTER_RESULT_TO_MAIN"
EVENT_EXECUTE_LOCK_RELEASED = "EVENT_EXECUTE_LOCK_RELEASED"
EVENT_EXECUTE_LOCK_UNAVAILABLE = "EVENT_EXECUTE_LOCK_UNAVAILABLE"

OBJ_TYPE_TRADE = "OBJ_TYPE_TRADE"
OBJ_TYPE_OPPPORTUNITY = "OBJ_TYPE_OPPPORTUNITY"
OBJ_TYPE_RESULT = "OBJ_TYPE_RESULT"
OBJ_TYPE_EVENT = "OBJ_TYPE_EVENT"

# EXCHANGES
EXCHANGE_BINANCE = "BINANCE"
EXCHANGE_BITTREX = "BITTREX"

# Mode
PRODUCTION_MODE = "production"
DRY_MODE = "dry"


# Time

TIME_1M = 60
TIME_5M = 60 * 5
TIME_24H = 60 * 60 * 24

WEB_SOCKETS_TOPIC_HEAD = "wss://stream.binance.com:9443/ws/"
WEB_SOCKETS_TOPIC_HEAD_LENGTH = len(WEB_SOCKETS_TOPIC_HEAD)
WEB_SOCKETS_TOPIC_TAIL = "@depth5"
WEB_SOCKETS_TOPIC_TAIL_LENGTH = len(WEB_SOCKETS_TOPIC_TAIL)
